/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform --types
Author: pizzaguyty (https://sketchfab.com/pizzaguyty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/palm-tree-tall-557ea8d4527f47e8bbc657e2764b7cab
Title: Palm Tree tall
*/

import { useTexture } from '@react-three/drei'

export function Floor(props: JSX.IntrinsicElements['group']) {
  const texture = useTexture('/floor.jpg')

  return (
    <group {...props} dispose={null}>
      <mesh position={[0, -0.3, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <planeBufferGeometry attach='geometry' args={[100, 100]} />
        <meshBasicMaterial map={texture} />
      </mesh>
    </group>
  )
}
