/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: objreader (https://sketchfab.com/objreader)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uscss-prometheus-flying-feeb1921cb9a4d0981e77b0ab6511940
Title: USCSS Prometheus flying
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function PrisonModel(props) {
  const scrollPosition = useScroll()

  const ref = React.useRef<Mesh>(null)
  useFrame(() => {
    if (ref.current) {
      ref.current.rotation.z = scrollPosition ? scrollPosition.offset : 0
      ref.current.rotation.y = scrollPosition ? scrollPosition.offset / 2 : 0
    }
  })

  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} ref={ref}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.bone} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.brass} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.brass} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.bridge_black} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.bridge_floor} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.bridge_panels} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.bridge_screens} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.bridge_wall} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.engine_glow} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.full_red} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.glass_bridge} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.grey_016} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.hull_black} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.hull_dark} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.hull_dark} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.hull_dark} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.hull_dark} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.hull_dark} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.hull_glow} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.hull_grey} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.hull_grey} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.hull_grey} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.hull_grey} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.hull_main} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.hull_main_side} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.hull_red} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.hull_yellow} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.hull_yellow} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.inside} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.l4_red_plain_3} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.hull_dark} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.hull_dark} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.full_red} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.red_line} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.seat} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.white_glow} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
