/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 blenderTest.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Fenster1: THREE.Mesh
    Fenster7: THREE.Mesh
    Fenster10: THREE.Mesh
    Fenster11: THREE.Mesh
    Fenster12: THREE.Mesh
    Fenster3: THREE.Mesh
    Fenster4: THREE.Mesh
    Fenster5: THREE.Mesh
    Fenster6: THREE.Mesh
    Fenster8: THREE.Mesh
    Fenster9: THREE.Mesh
    Fenster_1: THREE.Mesh
    Fenster_13: THREE.Mesh
    Fenster_14: THREE.Mesh
    Fenster_15: THREE.Mesh
    Fenster_16: THREE.Mesh
    Fenster_17: THREE.Mesh
    Fenster_18: THREE.Mesh
    Fenster_19: THREE.Mesh
    Fenster_2: THREE.Mesh
    Fenster_20: THREE.Mesh
    Fenster_21: THREE.Mesh
    Fenster_22: THREE.Mesh
    Fenster_23: THREE.Mesh
    Fenster_24: THREE.Mesh
    Fenster_25: THREE.Mesh
    Fenster_26: THREE.Mesh
    Fenster_27: THREE.Mesh
    Fenster_28: THREE.Mesh
    Fenster_29: THREE.Mesh
    Fenster_3: THREE.Mesh
    Fenster_4: THREE.Mesh
    Fenster_5: THREE.Mesh
    Fenster_6: THREE.Mesh
    Fenster_7: THREE.Mesh
    Fenster_8: THREE.Mesh
    Gebaeude_1: THREE.Mesh
    Gebaeude_2: THREE.Mesh
    Gebaeude_3: THREE.Mesh
    Gebaeude_4: THREE.Mesh
    Gebaeude_5: THREE.Mesh
    Tuer1: THREE.Mesh
    Tuer10: THREE.Mesh
    Tuer11: THREE.Mesh
    Tuer12: THREE.Mesh
    Tuer13: THREE.Mesh
    Tuer14: THREE.Mesh
    Tuer15: THREE.Mesh
    Tuer2: THREE.Mesh
    Tuer3: THREE.Mesh
    Tuer4: THREE.Mesh
    Tuer5: THREE.Mesh
    Tuer6: THREE.Mesh
    Tuer7: THREE.Mesh
    Tuer8: THREE.Mesh
    Tuer9: THREE.Mesh
    calathea_orbifolia_01_a: THREE.Mesh
    calathea_orbifolia_01_b: THREE.Mesh
    calathea_orbifolia_01_b1: THREE.Mesh
    calathea_orbifolia_01_c: THREE.Mesh
    calathea_orbifolia_01_c1: THREE.Mesh
    calathea_orbifolia_01_d: THREE.Mesh
    calathea_orbifolia_01_e: THREE.Mesh
    calathea_orbifolia_01_e1: THREE.Mesh
    rock_moss_set_02_rock07: THREE.Mesh
    rock_moss_set_02_rock08: THREE.Mesh
    rock_moss_set_02_rock09: THREE.Mesh
    rock_moss_set_02_rock15: THREE.Mesh
    rock_moss_set_02_rock17: THREE.Mesh
    rock_moss_set_02_rock10: THREE.Mesh
    rock_moss_set_02_rock11: THREE.Mesh
    rock_moss_set_02_rock12: THREE.Mesh
    rock_moss_set_02_rock13: THREE.Mesh
    rock_moss_set_02_rock16: THREE.Mesh
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_2001: THREE.Mesh
    Object_3001: THREE.Mesh
    Object_4001: THREE.Mesh
    Object_5001: THREE.Mesh
    pCube1_1: THREE.Mesh
    pCube1_2: THREE.Mesh
  }
  materials: {
    Fenster2: THREE.MeshStandardMaterial
    FensterundTueren: THREE.MeshStandardMaterial
    FrontWand: THREE.MeshStandardMaterial
    WandInnen: THREE.MeshStandardMaterial
    Default_Material: THREE.MeshStandardMaterial
    Boden: THREE.MeshStandardMaterial
    Treppen: THREE.MeshStandardMaterial
    calathea_orbifolia_01: THREE.MeshStandardMaterial
    rock_moss_set_02: THREE.MeshStandardMaterial
    initialShadingGroup: THREE.MeshStandardMaterial
    lambert2SG: THREE.MeshStandardMaterial
    lambert3SG: THREE.MeshStandardMaterial
    lambert5SG: THREE.MeshStandardMaterial
    Gras: THREE.MeshStandardMaterial
  }
}

export function PrisonModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/prison_model.glb') as GLTFResult

  const scrollPosition = useScroll()

  const ref = useRef<THREE.Group>(null)
  useFrame(() => {
    if (ref.current) {
      ref.current.rotation.y = scrollPosition ? scrollPosition.offset / 1.5 : 0
      ref.current.position.y = scrollPosition ? scrollPosition.offset / 2 : 0
    }
  })

  return (
    <group {...props} dispose={null}>
      <group scale={12.5}>
        <group scale={0.33}>
          <mesh
            geometry={nodes.Fenster1.geometry}
            material={materials.Fenster2}
            position={[-4.5, 0.54, 0.98]}
            scale={[0.21, 0.57, 0.07]}
          />
          <mesh
            geometry={nodes.Fenster7.geometry}
            material={materials.Fenster2}
            position={[5.19, 0.54, 0.98]}
            scale={[0.21, 0.57, 0.07]}
          />
          <mesh
            geometry={nodes.Fenster10.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster11.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster12.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster3.geometry}
            material={materials.Fenster2}
            position={[0, 0.49, -0.04]}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster4.geometry}
            material={materials.Fenster2}
            position={[0, 1.23, -0.04]}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster5.geometry}
            material={materials.Fenster2}
            position={[9.68, 1.23, -0.04]}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster6.geometry}
            material={materials.Fenster2}
            position={[9.68, 0.49, -0.04]}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster8.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster9.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_1.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_13.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_14.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_15.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_16.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_17.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_18.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_19.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_2.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_20.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_21.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_22.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_23.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_24.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_25.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_26.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_27.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_28.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_29.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_3.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_4.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_5.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_6.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_7.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Fenster_8.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <group position={[-0.13, 2.06, 0]} scale={[2.1, 2.64, 1.55]}>
            <mesh geometry={nodes.Gebaeude_1.geometry} material={materials.FrontWand} />
            <mesh geometry={nodes.Gebaeude_2.geometry} material={materials.WandInnen} />
            <mesh geometry={nodes.Gebaeude_3.geometry} material={materials.Default_Material} />
            <mesh geometry={nodes.Gebaeude_4.geometry} material={materials.Boden} />
            <mesh geometry={nodes.Gebaeude_5.geometry} material={materials.Treppen} />
          </group>
          <mesh geometry={nodes.Tuer1.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh
            geometry={nodes.Tuer10.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Tuer11.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Tuer12.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Tuer13.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Tuer14.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh
            geometry={nodes.Tuer15.geometry}
            material={materials.FensterundTueren}
            scale={0.2}
          />
          <mesh geometry={nodes.Tuer2.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh geometry={nodes.Tuer3.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh geometry={nodes.Tuer4.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh geometry={nodes.Tuer5.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh geometry={nodes.Tuer6.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh geometry={nodes.Tuer7.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh geometry={nodes.Tuer8.geometry} material={materials.FensterundTueren} scale={0.2} />
          <mesh geometry={nodes.Tuer9.geometry} material={materials.FensterundTueren} scale={0.2} />
        </group>
      </group>
      <group position={[49.82, 0, 3.5]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-24.27, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.initialShadingGroup} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.lambert2SG} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.lambert3SG} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.lambert5SG} />
        </group>
      </group>
      <group position={[0, 0, 6.92]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-24.27, 0, 0]}>
          <mesh geometry={nodes.Object_2001.geometry} material={materials.initialShadingGroup} />
          <mesh geometry={nodes.Object_3001.geometry} material={materials.lambert2SG} />
          <mesh geometry={nodes.Object_4001.geometry} material={materials.lambert3SG} />
          <mesh geometry={nodes.Object_5001.geometry} material={materials.lambert5SG} />
        </group>
      </group>
      <group position={[0, -0.27, 2.65]} scale={[61.24, 0.47, 26.88]}>
        <mesh geometry={nodes.pCube1_1.geometry} material={materials.WandInnen} />
        <mesh geometry={nodes.pCube1_2.geometry} material={materials.Gras} />
      </group>
      <mesh
        geometry={nodes.calathea_orbifolia_01_a.geometry}
        material={materials.calathea_orbifolia_01}
        position={[-0.16, 0.09, 4.92]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.calathea_orbifolia_01_b.geometry}
        material={materials.calathea_orbifolia_01}
        position={[20.65, 0.15, 5.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.calathea_orbifolia_01_b1.geometry}
        material={materials.calathea_orbifolia_01}
        position={[9.06, 0.15, 4.98]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.calathea_orbifolia_01_c.geometry}
        material={materials.calathea_orbifolia_01}
        position={[21.61, 0.15, 5.42]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.calathea_orbifolia_01_c1.geometry}
        material={materials.calathea_orbifolia_01}
        position={[10.02, 0.15, 5.38]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.calathea_orbifolia_01_d.geometry}
        material={materials.calathea_orbifolia_01}
        position={[-5.27, 0, 10.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.calathea_orbifolia_01_e.geometry}
        material={materials.calathea_orbifolia_01}
        position={[20.78, 0.15, 5.35]}
        rotation={[-Math.PI / 2, 0, -1.81]}
        scale={100}
      />
      <mesh
        geometry={nodes.calathea_orbifolia_01_e1.geometry}
        material={materials.calathea_orbifolia_01}
        position={[9.19, 0.15, 5.31]}
        rotation={[-Math.PI / 2, 0, -1.81]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock07.geometry}
        material={materials.rock_moss_set_02}
        position={[-27.21, 0.36, 12.77]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={67.9}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock08.geometry}
        material={materials.rock_moss_set_02}
        position={[-20.4, 0, 4.14]}
        rotation={[-Math.PI / 2, 0, -0.38]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock09.geometry}
        material={materials.rock_moss_set_02}
        position={[22.82, 0, 5.17]}
        rotation={[-Math.PI / 2, 0, 0.97]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock15.geometry}
        material={materials.rock_moss_set_02}
        position={[20.05, 0.14, -6.73]}
        rotation={[-Math.PI / 2, 0, 0.96]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock17.geometry}
        material={materials.rock_moss_set_02}
        position={[9.81, 0.04, 4.75]}
        rotation={[-Math.PI / 2, 0, 0.12]}
        scale={64.56}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock10.geometry}
        material={materials.rock_moss_set_02}
        position={[26.88, 0.16, 13.18]}
        rotation={[-Math.PI / 2, 0, 0.55]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock11.geometry}
        material={materials.rock_moss_set_02}
        position={[-28.03, -0.13, -5.4]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock12.geometry}
        material={materials.rock_moss_set_02}
        position={[-26.17, 0.08, -6.95]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock13.geometry}
        material={materials.rock_moss_set_02}
        position={[23.59, 0.34, 4.69]}
        rotation={[-Math.PI / 2, 0, -0.67]}
        scale={100}
      />
      <mesh
        geometry={nodes.rock_moss_set_02_rock16.geometry}
        material={materials.rock_moss_set_02}
        position={[20.82, 0.34, -7.2]}
        rotation={[-Math.PI / 2, 0, -0.68]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/prison_model.glb')
