/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.glb --transform --types
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Fenster_27: THREE.Mesh
    Fenster_29: THREE.Mesh
    Fenster7: THREE.Mesh
    Fenster4: THREE.Mesh
    Fenster_3: THREE.Mesh
    Tuer6: THREE.Mesh
    Fenster12: THREE.Mesh
    Fenster_14: THREE.Mesh
    Fenster_16: THREE.Mesh
    Fenster_1: THREE.Mesh
    Tuer2: THREE.Mesh
    Gebaeude: THREE.Mesh
    Gebaeude_1: THREE.Mesh
    Gebaeude_2: THREE.Mesh
    Gebaeude_3: THREE.Mesh
    Gebaeude_4: THREE.Mesh
    Tuer3: THREE.Mesh
    Fenster_28: THREE.Mesh
    Fenster_26: THREE.Mesh
    Fenster9: THREE.Mesh
    Fenster_2: THREE.Mesh
    Tuer8: THREE.Mesh
    Fenster_4: THREE.Mesh
    Fenster_23: THREE.Mesh
    Tuer15: THREE.Mesh
    Fenster_24: THREE.Mesh
    Fenster10: THREE.Mesh
    Tuer5: THREE.Mesh
    Fenster5: THREE.Mesh
    Fenster_15: THREE.Mesh
    Fenster_7: THREE.Mesh
    Fenster_17: THREE.Mesh
    Fenster_21: THREE.Mesh
    Fenster_20: THREE.Mesh
    Fenster_6: THREE.Mesh
    Fenster_25: THREE.Mesh
    Tuer10: THREE.Mesh
    Fenster_18: THREE.Mesh
    Fenster3: THREE.Mesh
    Tuer9: THREE.Mesh
    Tuer13: THREE.Mesh
    Fenster6: THREE.Mesh
    Fenster_22: THREE.Mesh
    Tuer14: THREE.Mesh
    Fenster_5: THREE.Mesh
    Fenster1: THREE.Mesh
    Fenster_13: THREE.Mesh
    Tuer1: THREE.Mesh
    Fenster_19: THREE.Mesh
    Tuer11: THREE.Mesh
    Fenster8: THREE.Mesh
    Tuer4: THREE.Mesh
    Fenster_8: THREE.Mesh
    Fenster11: THREE.Mesh
    Tuer12: THREE.Mesh
    Tuer7: THREE.Mesh
  }
  materials: {
    FensterundTueren: THREE.MeshStandardMaterial
    Fenster2: THREE.MeshStandardMaterial
    FrontWand: THREE.MeshStandardMaterial
    WandInnen: THREE.MeshStandardMaterial
    Default_Material: THREE.MeshStandardMaterial
    Boden: THREE.MeshStandardMaterial
    Treppen: THREE.MeshStandardMaterial
  }
}

export function PrisonModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/prison-model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Fenster_27.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_29.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster7.geometry} material={materials.Fenster2} />
      <mesh geometry={nodes.Fenster4.geometry} material={materials.Fenster2} />
      <mesh geometry={nodes.Fenster_3.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer6.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster12.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_14.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_16.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_1.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer2.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer3.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_28.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_26.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster9.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_2.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer8.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_4.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_23.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer15.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_24.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster10.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer5.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster5.geometry} material={materials.Fenster2} />
      <mesh geometry={nodes.Fenster_15.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_7.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_17.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_21.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_20.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_6.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_25.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer10.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_18.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster3.geometry} material={materials.Fenster2} />
      <mesh geometry={nodes.Tuer9.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer13.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster6.geometry} material={materials.Fenster2} />
      <mesh geometry={nodes.Fenster_22.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer14.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_5.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster1.geometry} material={materials.Fenster2} />
      <mesh geometry={nodes.Fenster_13.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer1.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_19.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer11.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster8.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer4.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster_8.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Fenster11.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer12.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Tuer7.geometry} material={materials.FensterundTueren} />
      <mesh geometry={nodes.Gebaeude.geometry} material={materials.FrontWand} />
      <mesh geometry={nodes.Gebaeude_1.geometry} material={materials.WandInnen} />
      <mesh geometry={nodes.Gebaeude_2.geometry} material={materials.Default_Material} />
      <mesh geometry={nodes.Gebaeude_3.geometry} material={materials.Boden} />
      <mesh geometry={nodes.Gebaeude_4.geometry} material={materials.Treppen} />
    </group>
  )
}

useGLTF.preload('/prison-model.glb')
