/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 blenderTest.glb --transform --types
*/

import { Center, Text3D, useGLTF } from '@react-three/drei'
import * as language from './PrisonModelCanvas_lang'

export function TitleText(props: JSX.IntrinsicElements['group']) {
  const fontUrl = './3dfont.json'

  // TODO: Real Headline
  return (
    <Center top disableY>
      <Text3D font={fontUrl} position={[0, -35, 0]} size={5} bevelThickness={10}>
        {language.HEADING}
      </Text3D>
    </Center>
  )
}

useGLTF.preload('/prison_model.glb')
