/* eslint-disable camelcase */
export const H1_Unabhaengigkeit = 'Unabhängigkeit & Armut'
export const T1_Unabhaengigkeit =
  'Kambodscha galt lange als wichtige Kolonie Frankreichs und erreichte erst im Jahr 1954 die nationale Unabhängigkeit im Rahmen der Indochinakonferenz. Das Land war zu diesem Zeitpunkt von Unruhen und großer Unzufriedenheit in der Bevölkerung geprägt. So hatten zuvor eine Vielzahl von Bauern aus dem Nachbarland Vietnam von der französischen Kolonialverwaltung Grundstücke in Kambodscha als Entschädigung für zuvor beschlagnahmte Gebiete erhalten. Mit der Unabhängigkeit Kambodschas waren diese Bauern aufgrund neuer Kriterien zur Staatsangehörigkeit plötzlich enteignet, was zu Unmut bei den Betroffenen führte. Darüber hinaus fiel der neuen Führung die Zusammenführung und Integration der diversen Bevölkerungsgruppen und Kulturkreise in Kambodscha schwer. Dazu war ein großer Teil der Bürger, insbesondere auf dem Land, von großer Armut betroffen; der Anteil der Landbevölkerung ohne Grundbesitz stieg von 4 % im Jahr 1950 auf 20 % im Jahr 1970.'

export const H2_Prinz = 'Prinz Norodom Sihanouk & die Opposition'
export const T2_Prinz =
  'Als Folge der Unabhängigkeit und der Notwendigkeit einer eigenen politischen Führung wurde der Prinz Norodom Sihanouk im Jahr 1955 in einer manipulierten Wahl Machthaber und unterdrückte in seiner Amtszeit systematisch die Opposition. Diese bestand unter anderem aus der kommunistischen Partei Kampucheas (KPK), in der die antivietnamesischen und antimonarchistischen Hardliner durch den Führungsstil von Norodom Sihanouk immer mehr Zuspruch bekamen. Ab 1964 entstanden aus der politischen Opposition gewaltsame Guerillabewegungen, die sich gegen das Regime vom herrschenden Norodom Sihanouk richteten.'

export const H3_Aufstand = 'Der Samlaut-Aufstand'
export const T3_Aufstand =
  'Am 11. März 1967 brach im Bezirk Samlaut in der Provinz Battambang ein gewaltsamer Aufstand aus. Der sogenannte Samlaut-Aufstand gilt als der Beginn des kambodschanischen Bürgerkriegs. In diesem Krieg standen auf der einen Seite die Regierungstruppen der Republik Khmer unter dem herrschenden Norodom Sihanouk. Auf der anderen Seite standen die Nationale Einheitsfront von Kampuchea (FUNK) und die KPK unter der Führung von Pol Pot. Diese wurden von Norodom Sihanouk verallgemeinert auch als “Rote Khmer” bezeichnet, später sind damit ausschließlich die Pol Pot zugehörigen Mitglieder der KPK gemeint. Am 1. März 1970 wurde Norodom Sihanouk schließlich durch den General Lon Nol gestürzt, welcher selbst keiner Partei angehörig war. Während die Städte durch Lon Nols Regierungskräfte kontrolliert wurden, standen ländliche Gebiete unter Kontrolle der Roten Khmer.'

export const H4_Vietnam = 'Der Einfluss des Vietnamkriegs'
export const T4_Vietnam =
  'Parallel zu den Geschehnissen in Kambodscha wurde von etwa 1955 bis 1975 der Vietnamkrieg geführt. Im Zuge dessen wurde von 1969 bis 1973 auch Kambodscha von den USA bombardiert, um die Versorgungswege nach Vietnam zu zerstören. So wurde das Land mit in den Vietnamkrieg hineingezogen. Trotz des Bombardements kambodschanischer Landstriche galt Lon Nol als Verbündeter der USA und wurde von diesen wirtschaftlich und militärisch unterstützt. Da vor allem landwirtschaftliche Flächen zerstört wurden, wandten sich die Menschen auf dem Land von den USA ab und den Roten Khmer zu. Auch wenn die amerikanischen Kräfte im Jahr 1973 abzogen, nahm der Konflikt zwischen den kommunistischen Roten Khmer und der von den USA unterstützten Regierung weiter zu. Währenddessen hatten manche Kambodschaner jedoch bereits den Eindruck, dass die Roten Khmer sich immer mehr fanatisierten, da sie jedes Friedensangebot sofort ablehnten und sich nicht im Geringsten um ihre eigenen Verluste oder zivile Opfer der Kämpfe sorgten.'
