export const H1_PrisonLife = 'Das Gefängnis und Folterzentrum S-21'
export const T1_PrisonLife = 'Man kann nur noch erahnen, dass das Toul Sleng Gefängnis der Roten Khmer früher einmal eine Schule in Phnom Penh war. Das Gebäude ist von Stacheldrahtzäunen bedeckt, die Fenster sind vergittert und die Türen verbarrikadiert. Selbst die Balkons vom ersten und zweiten Stock sind durch Stacheldraht gesichert und sollen nicht nur dafür sorgen das keiner entkommen kann, sondern auch dass niemand sich das Leben nehmen kann, ohne zuvor ein Geständnis abgelegt zu haben. Hier werden Menschen inhaftiert, verhört und gefoltert, bevor sie zur Hinrichtung gebracht werden.'

export const H2_PrisonLife = 'Tägliche Misshandlung'
export const T2_PrisonLife = 'Die Gefangenen werden tagtäglich auf unmenschlichste weise physisch und psychisch misshandelt. Die Gefängniswärter schrecken vor nichts zurück und nutzen ihre Überlegenheit schamlos aus. Die Rote Khmer erhoffte sich durch die Folter von den Inhaftierten Informationen über vermeintliche Feinde des Regimes zu erlangen. Oft wurden unschuldige Menschen beschuldigt Spione oder Mitglieder oppositioneller Gruppen zu sein, dabei wurde keine Gesellschaftliche Gruppe vom Regime verschont.'

export const H3_PrisonLife = 'Folter in Tuol Sleng'
export const T3_PrisonLife = 'Die Folter in Tuol Sleng ist ein Teil eines systematischen Versuchs, die Gefangenen zu brechen und sie dazu zu bringen, Geständnisse und Informationen preiszugeben. Hier werden einige der Foltermethoden aus dem Gefängnis aufgelistet, dabei geht es darum ein Verständnis für die Gräueltaten zu schaffen und die Opfer zu ehren, die unter solchen Methoden gelitten haben.'
export const T3_1_PrisonLife = 'Elektroschocks: Gefangene wurden mit Stromschlägen gefoltert, indem man ihnen Elektroden an verschiedenen Stellen des Körpers anbrachte. Häufig wurden die Elektroden an sensiblen Stellen des Körpers befestigt, wie zum Beispiel Fingern, Zehen, Ohren oder auch Genitalien. Die Folgen dieser Foltermethoden waren nicht nur körperlich, sondern hinterlassen auch enorme geistige Schäden.'
export const T3_2_PrisonLife = 'Ertränkung: Gefangene wurden in Eimer oder Tanks mit Wasser getaucht, bis sie fast ertrunken waren, bevor sie wieder herausgezogen wurden. Bei dieser Foltermethode sind die Gesundheitsprobleme verehrend, Atemwegserkrankungen über Herz-Kreislauf-Erkrankungen bis hin zu Organversagen oder Hirnschäden. Darüber hinaus erleiden die Opfer Traumata die ein Leben lang anhalten können und deren Alltag stark beeinträchtigen können.'
export const T3_3_PrisonLife = 'Schlafentzug: Gefangene wurden gezwungen, tagelang ohne Schlaf auszukommen, um sie zu zermürben und zu brechen. Schlafentzug kann körperliche Symtome wie Kopfschmerzen oder Herz-Kreislauf-Probleme verursachen, aber auch psychische Symptome wie Halluzinationen und Verwirrtheit können auftreten. Dabei kommt es auch darauf an wie lange der Schlafentzug anhält. In der Regel kann der menschliche Körper nur bis zu 11 Tage ohne Schlaf überleben.'
export const T3_4_PrisonLife = 'Zwangsernährung: Gefangene wurden zwangsernährt, indem ihnen durch eine Nasensonde Nahrung oder Flüssigkeiten direkt in den Magen gepumpt wurden. Dies wurde oft mit rohem Reis, Salzwasser oder anderen unverdaulichen Substanzen durchgeführt und verursacht starke Schmerzen. Diese Methode zielt vor allem auf eine psychische Folter ab. Die Opfer haben ein Gefühl der Machtlosigkeit, Demut und Entfremdung, auch so sollen die Gefangenen gefügiger werden.'
export const T3_5_PrisonLife = 'Verwendung von chirurgischen Werkzeugen: Gefangene wurden mit chirurgischen Werkzeugen wie Zangen, Messern und Sägen gefoltert, um sie zu verletzen und ihnen Schmerzen zuzufügen. Diese Art der Folter ist so vielfältig, dass es unmöglich ist alles aufzulisten, folgend stehen die hier aufgelistet Methoden nur als Beispiel. Körperteile wie Finger- und Zehennägel, aber auch Brustwarzen wurden abgerissen. Mit Spritzen wurden den Opfern Gifte oder unangenehme Substanzen verabreicht. Mit zu den gewaltätigsten Arten der Folter gehörte die teilweise Häutung von Opfern, welches bis hin zur Skalpierung führte.'